---
- name: k3s | Render k3s arguments from variables
  set_fact:
    k3s_args: "{{ lookup('template', 'k3s_args.j2') }}"

- name: k3s | Configuring k3s with the following rendered arguments
  debug:
    msg: "{{ k3s_args }}"

- name: k3s | Create the k3s config directory
  file:
    path: "{{ k3s_etc_dir }}"
    owner: root
    group: root
    mode: "0755"
    state: directory

- name: k3s | Create the k3s environment file
  template:
    src: k3s_env_file.j2
    dest: "{{ k3s_openrc_env }}"
    owner: root
    group: root
    mode: "600"

- name: k3s | Create the openrc service file
  template:
    src: openrc_service.j2
    dest: "{{ k3s_openrc_service }}"
    owner: root
    group: root
    mode: "0755"

- name: k3s | Create logrotate configuration
  template:
    src: k3s_logrotate.j2
    dest: "{{ k3s_logrotate_dir }}/{{ k3s_system_name }}"
    owner: root
    group: root
    mode: "0644"

- name: k3s | Start and enable the service
  service:
    name: "{{ k3s_system_name }}"
    enabled: true
    state: started
    use: openrc
