---
scenario:
  name: aws-ec2-ubuntu1804
dependency:
  name: galaxy
driver:
  name: ec2
lint:
  name: yamllint
platforms:
  - name: Ubuntu1804-server
    image: ami-079f96ce4a4a7e1c7
    instance_type: t3.nano
    ebs_optimized: true
    vpc_subnet_id: subnet-fc36a4d3
    groups:
      - k3s_servers
  - name: Ubuntu1804-agent
    image: ami-079f96ce4a4a7e1c7
    instance_type: t3.nano
    ebs_optimized: true
    vpc_subnet_id: subnet-fc36a4d3
    groups:
      - k3s_agents
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  options:
    D: True
  connection_options:
    ansible_ssh_user: ubuntu
  playbooks:
    converge: ./playbook.yml
  inventory:
    group_vars:
      k3s_servers:
        k3s_role: server
        k3s_server_bind_address: "{{ default_ipv4.address }}"
        k3s_server_https_listen_port: 6443
        tls_san:
          - "{{ hostvars['Ubuntu1804-server']['ansible_host'] }}"
      k3s_agents:
        k3s_role: agent
        k3s_url: "https://{{ hostvars['Ubuntu1804-server']['ansible_host'] }}:6443"
        k3s_cluster_secret: testSecret1234
        k3s_token: testToken1234
    host_vars:
      Ubuntu1804-server:
        k3s_node_name: Ubuntu1804-server
      Ubuntu1804-agent:
        k3s_node_name: Ubuntu1804-agent
verifier:
  name: testinfra
  directory: ../tests/
  lint:
    name: flake8
