---
scenario:
  name: aws-ec2-ubuntu1804
dependency:
  name: galaxy
name: ec2
  ssh_connection_options:|
    o ControlPath=~/.ansible/cp/%r@%h-%p
lint:
  name: yamllint
platforms:
  - name: Ubuntu1804-server
    image: ami-079f96ce4a4a7e1c7
    instance_type: t3.nano
    vpc_subnet_id: subnet-fc36a4d3
    groups:
      - k3s_servers
  - name: Ubuntu1804-agent
    image: ami-079f96ce4a4a7e1c7
    instance_type: t3.nano
    vpc_subnet_id: subnet-fc36a4d3
    groups:
      - k3s_agents
    networks:
      - name: molecule_k3s_ubuntu
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  playbooks:
    converge: ../playbook.yml
  inventory:
    group_vars:
      all:
        k3s_cluster_secret: testSecret1234
        k3s_token: testToken1234
      k3s_servers:
        k3s_role: server
        k3s_server_bind_address: 0.0.0.0
      k3s_agents:
        k3s_role: agent
    host_vars:
      Ubuntu1804-server:
        k3s_node_name: Ubuntu1804-server
        k3s_server_https_listen_port: 6443
      Ubuntu1804-agent:
        k3s_node_name: Ubuntu1804-agent
        k3s_url: https://Ubuntu1804-server:6443
      Alpine39-server:
        k3s_node_name: Alpine39-server
        k3s_server_https_listen_port: 6443
      Alpine39-agent:
        k3s_node_name: Alpine39-agent
        k3s_url: https://Alpine39-server:7443
verifier:
  name: testinfra
  lint:
    name: flake8
