---
scenario:
  name: aws-ec2-alpine39
dependency:
  name: galaxy
driver:
  name: ec2
lint:
  name: yamllint
platforms:
  - name: Alpine39-server
    image: ami-05c8c48601c2303af
    instance_type: t3.nano
    vpc_subnet_id: subnet-fc36a4d3
    groups:
      - k3s_servers
  - name: Alpine39-agent
    image: ami-05c8c48601c2303af
    instance_type: t3.nano
    ebs_optimized: true
    vpc_subnet_id: subnet-fc36a4d3
    groups:
      - k3s_agents
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  playbooks:
    converge: ./playbook.yml
  connection_options:
    ansible_ssh_user: alpine
  inventory:
    group_vars:
      all:
        k3s_cluster_secret: testSecret1234
        k3s_token: testToken1234
      k3s_servers:
        k3s_role: server
        k3s_server_bind_address: 0.0.0.0
      k3s_agents:
        k3s_role: agent
    host_vars:
      Alpine39-server:
        k3s_node_name: Alpine39-server
        k3s_server_https_listen_port: 6443
      Alpine39-agent:
        k3s_node_name: Alpine39-agent
        k3s_url: "https://{{ hostvars['Alpine39-server']['ansible_host'] }}:6443"
verifier:
  name: testinfra
  lint:
    name: flake8
