---
- name: k3s_systemd_daemon_reload
  systemd:
    name: "{{ k3s_systemd_service_name }}"
    daemon_reload: true

- name: k3s_systemd_restart
  systemd:
    name: "{{ k3s_systemd_service_name }}"
    state: restared
