---
scenario:
  name: aws-ec2-funtoo13
dependency:
  name: galaxy
driver:
  name: ec2
lint:
  name: yamllint
platforms:
  - name: Funtoo13-server
    image: ami-0b7b6f8dcddfdabb8
    instance_type: t2.micro
    vpc_subnet_id: subnet-fc36a4d3
    groups:
      - k3s_servers
  - name: Funtoo13-agent
    image: ami-0b7b6f8dcddfdabb8
    instance_type: t2.micro
    ebs_optimized: true
    vpc_subnet_id: subnet-fc36a4d3
    groups:
      - k3s_agents
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  options:
    D: True
  connection_options:
    ansible_ssh_user: ec2-user
  playbooks:
    converge: ./playbook.yml
  inventory:
    group_vars:
      k3s_servers:
        k3s_role: server
        k3s_server_bind_address: "{{ default_ipv4.address }}"
        k3s_server_https_listen_port: 6443
        tls_san:
          - "{{ hostvars['Funtoo13-server']['ansible_host'] }}"
      k3s_agents:
        k3s_role: agent
        k3s_url: "https://{{ hostvars['Funtoo13-server']['ansible_host'] }}:6443"
        k3s_cluster_secret: testSecret1234
        k3s_token: testToken1234
    host_vars:
      Funtoo13-server:
        k3s_node_name: Funtoo13-server
      Funtoo13-agent:
        k3s_node_name: Funtoo13-agent
verifier:
  name: testinfra
  directory: ../tests/
  lint:
    name: flake8
