---
- name: Prepare
  hosts: all
  gather_facts: false
  tasks:
    - name: Install python for Ansible
      raw: test -e /usr/bin/python || (ego sync && emerge dev-lang/python:3.4)
      become: true
      changed_when: false
